spring:
  application:
    name: simple-consumer
  jmx:
    default-domain: simple-consumer
  cloud:
    stream:
      kafka:
        binder:
          brokers: cloudTest:19092
          zk-nodes: cloudTest:22182
          auto-create-topics: true
          min-partition-count: 1
      bindings:
        input:
          destination: wordCount-output
          contentType: text/plain
eureka:
  client:
    enabled: false