server:
  port: 18082
spring:
  application:
    name: wordcount-processor
  jmx:
    default-domain: wordcount-processor
  cloud:
    stream:
      kafka:
        streams:
          binder:
            brokers: cloudTest:19092
            zk-nodes: cloudTest:22182
            auto-create-topics: true
            min-partition-count: 1
      bindings:
        input:
          destination: wordCount-producer
          contentType: application/json
        output:
          destination: wordCount-output
          contentType: application/json

eureka:
  client:
    enabled: false