server:
  port: 8082
logging:
  config: classpath:logback.xml

spring:
  application:
    name: ok-service
  jmx:
    default-domain: OKService_client1

eureka:
  client:
    enabled: false

ok-service-meta:
  clientId: client2