server:
  port: 8080
logging:
  config: classpath:logback.xml

spring:
  application:
    name: OKRibbonService
  jmx:
    default-domain: simple_static_ribbon_service

eureka:
  client:
    enabled: false


ribbon:
  eureka:
    enabled: false
  eager-load:
    enabled: true
    clients: okservice

ok-service:
  ribbon:
    listOfServers: localhost:8081,localhost:8082
    ServerListRefreshInterval: 15000
