server:
  port: 18082
spring:
  application:
    name: wordcount-processor
  jmx:
    default-domain: wordcount-processor
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
  cloud:
    stream:
      kafka:
        streams:
          binder:
            brokers: cloudTest:19092
            zk-nodes: cloudTest:22182
            auto-create-topics: true
            min-partition-count: 1
            configuration:
              default:
                key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          bindings:
            Branch_DEMO:
              consumer:
                applicationId: stream-branch
            INTERACTIVE_QUERY:
              consumer:
                applicationId: stream-interactive-query
            input:
              consumer:
                applicationId: wordCount
      bindings:
        Branch_DEMO:
          destination: stream-branch
          contentType: application/json
        INTERACTIVE_QUERY:
          destination: stream-interactive-query
          contentType: application/json
        Branch_output_1:
          destination: Branch_output_1
          contentType: text/plain
        Branch_output_2:
          destination: Branch_output_2
          contentType: text/plain
        Branch_output_3:
          destination: Branch_output_3
          contentType: text/plain
        input:
          destination: wordCount-producer
          contentType: application/json
        output:
          destination: wordCount-output
          contentType: application/json

eureka:
  client:
    enabled: false