spring:
  application:
    name: simple-consumer
  jmx:
    default-domain: simple-consumer
  cloud:
    stream:
      kafka:
        binder:
          brokers: cloudTest:19092
          zk-nodes: cloudTest:22182
          auto-create-topics: true
          min-partition-count: 1
          configuration:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bindings:
        branch_demo_1:
          destination: Branch_output_1
          contentType: text/plain
        branch_demo_2:
          destination: Branch_output_2
          contentType: text/plain
        branch_demo_3:
          destination: Branch_output_3
          contentType: text/plain

eureka:
  client:
    enabled: false