server:
  port: 8080
logging:
  .config: classpath:logback.xml

management:
  endpoints:
    web:
      exposure:
        include:
        - 'hystrix.stream'
        - 'info'
spring:
  application:
    name: simplest-hystrix-server
  jmx:
    default-domain: simplest-hystrix-server

