server:
  port: 8080
logging:
  config: classpath:logback.xml

spring:
  application:
    name: simple_config_server
  profiles:
    active:
    - native
  jmx:
    default-domain: simple_config_server
  cloud:
    config:
      server:
        native:
          search-locations:
          - file:../../config-repo

eureka:
  client:
    enabled: false


