server:
  port: 18081
spring:
  application:
    name: simple-producer
  jmx:
    default-domain: simple-producer
  cloud:
    stream:
      kafka:
        binder:
          brokers: cloudTest:19092
          zk-nodes: cloudTest:22182
          auto-create-topics: true
      bindings:
        output:
          destination: textPlain
          content-type: text/plain
          producer:
            partitionCount: 1
eureka:
  client:
    enabled: false