server:
  port: 18082
spring:
  application:
    name: custombing-custom
  jmx:
    default-domain: custombing-custom
  cloud:
    stream:
      kafka:
        binder:
          brokers: cloudTest:19092
          zk-nodes: cloudTest:22182
          auto-create-topics: true
          min-partition-count: 1
      bindings:
        myInput:
          destination: textPlain
          group: s1
          consumer:
            autoCommitOffset: false
            concurrency: 1
            partitioned: false
        myOutput:
          destination: sendLevel
          group: s2
          content-type: text/plain
          producer:
            partitionCount: 1
eureka:
  client:
    enabled: false