server:
  port: 8081

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8080/me

eureka:
  client:
    enabled: false

logging:
  level:
    org.springframework.security: debug

spring:
  jmx:
    default-domain: oauth2_simple_resource_server