server:
  port: 8081

eureka:
  client:
    enabled: false

logging:
  level:
    org.springframework.security: debug

spring:
  jmx:
    default-domain: oauth2_simple_resource_server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json