server:
  port: 8080

eureka:
  client:
    enabled: false

logging:
  level:
    org.springframework.security: debug

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret

spring:
  jmx:
    default-domain: oauth2_simple_server