server:
  port: 28761
logging:
  config: classpath:logback.xml

eureka:
  instance:
    metadata-map:
      mykey: customizedValue
  client:
    serviceUrl:
      defaultZone: http://zone1:18761/eureka/
info:
  app:
    name: simplest-eureka-client
    description: this is a very simple eureka client
    version: 1.0.0
  java-vendor: ${java.specification.vendor}

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: simplest-eureka-client
  jmx:
    default-domain: simplest-eureka-client_server_1_client_1

