server:
  port: 18762
logging:
  .config: classpath:logback.xml

eureka:
  instance:
    hostname: zone2
  client:
    serviceUrl:
      defaultZone: http://zone1:18761/eureka/

spring:
  application:
    name: multi-eureka-server
  jmx:
    default-domain: simplest-eureka-server_2

