server:
  port: 8762
logging:
  config: classpath:logback.xml

eureka:
   instance:
      metadata-map:
          mykey: customizedValue


spring:
  application:
    name: simplest-eureka-client
  jmx:
    default-domain: simplest-eureka-client

