server:
  port: 8081
logging:
  config: classpath:logback.xml

spring:
  application:
    name: ReactiveOKService
  jmx:
    default-domain: Reactive_OKService_feign_demo_client1

ok-service-meta:
  clientId: client1
