server:
  port: 18081
spring:
  application:
    name: simple-producer
  jmx:
    default-domain: simple-producer
  cloud:
    stream:
      schemaRegistryClient:
        endpoint: http://cloudTest:19093
      kafka:
        binder:
          brokers: cloudTest:19092
          zk-nodes: cloudTest:22182
          auto-create-topics: true
          schema.registry.url: http://cloudTest:19093
      bindings:
        output:
          destination: simpleTest
          content-type: application/*+avro
eureka:
  client:
    enabled: false