spring:
  application:
    name: simple-consumer
  jmx:
    default-domain: simple-consumer
  cloud:
    stream:
      schemaRegistryClient:
        endpoint: http://cloudTest:19093
      kafka:
        binder:
          brokers: cloudTest:19092
          zk-nodes: cloudTest:22182
          auto-create-topics: true
          key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
          value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
          schema.registry.url: http://cloudTest:19093
      bindings:
        input:
          destination: simpleTest
          content-type: application/*+avro
          group: s1
          consumer:
            autoCommitOffset: false
            concurrency: 1
            partitioned: false
eureka:
  client:
    enabled: false