server:
  port: 8082
spring:
  cloud:
    function.definition: log
    stream:
      bindings:
        log-out-0:
          destination: avroTopic
      kafka:
        binder:
          producerProperties:
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema.registry.url: http://localhost:8081
      default:
        group: test
        producer:
          useNativeEncoding: true
