server:
  port: 18763
logging:
  .config: classpath:logback.xml

eureka:
  instance:
    hostname: zone3
  client:
    serviceUrl:
      defaultZone: http://zone1:18761/eureka/,http://zone2:18762/eureka/

spring:
  application:
    name: multi-eureka-server
  jmx:
    default-domain: simplest-eureka-server_3



