server:
  port: 8080
logging:
  config: classpath:logback.xml

spring:
  application:
    name: OKRibbonService
  jmx:
    default-domain: simple_static_ribbon_service
  cloud:
    loadbalancer:
      retry:
        enabled: true

ribbon:
  MaxAutoRetries: 100
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
  ConnectTimeout: 99999


eureka:
  instance:
    hostname: sayHi
    preferIpAddress: true #this was done for example purposes only
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

ok-service:
  ribbon:
    MaxAutoRetries: 100
    MaxAutoRetriesNextServer: 1
    retryableStatusCodes: 500
    ReadTimeout: 99999
    ServerListRefreshInterval: 15000