server:
  port: 8080
logging:
  config: classpath:logback.xml

spring:
  application:
    name: OKRibbonService
  jmx:
    default-domain: simple_static_ribbon_service

eureka:
  instance:
    hostname: sayHi
    preferIpAddress: true #this was done for example purposes only
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka