server:
  port: 8080

spring:
  application:
    name: simple_feign_server
  jmx:
    default-domain: reactive_feign_server

feign:
  hystrix:
    enabled: true

reactive:
  remote: ReactiveOKService
logging:
  level:
    com.springframework.cloud: warn
    com.netflix.discovery: warn
    com.netflix.hystrix: debug
    org.springframework.web: debug