server:
  port: 8080

spring:
  application:
    name: simple_feign_server
  jmx:
    default-domain: reactive_feign_server


feign:
  hystrix:
    enabled: true


reactive:
  remote: ReactiveOKService
logging:
  level:
    com.springframework.cloud: debug
    com.netflix.discovery: warn
    com.netflix.hystrix: debug
    com.netflix.ribbon: debug
    org.springframework.web: debug

