spring:
  application:
    name: simple-consumer
  jmx:
    default-domain: simple-consumer
  cloud:
    stream:
      kafka:
        binder:
          brokers: cloudTest:19092
          zk-nodes: cloudTest:22182
          auto-create-topics: true
          min-partition-count: 1
        default:
          consumer:
            autoCommitOffset: false
      bindings:
        input:
          destination: textPlain
          group: s1
eureka:
  client:
    enabled: false