server:
  port: 8080
logging:
  config: classpath:logback.xml

spring:
  application:
    name: hystrix_feign_server
  jmx:
    default-domain: hystrix_feign_server

feign:
  hystrix:
    enabled: true

eureka:
  client:
    enabled: false


feign-meta:
  okService: OKService
  url: http://localhost:8081