server:
  port: 38756
logging:
  config: classpath:logback.xml

spring:
  application:
    name: OKService
  jmx:
    default-domain: OKService_feign_demo_client1


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


ok-service-meta:
  clientId: client1
