server:
  port: 8081
logging:
  config: classpath:logback.xml

spring:
  application:
    name: OKService
  jmx:
    default-domain: OKService_feign_demo_client1


eureka:
  client:
    enabled: false

ok-service-meta:
  clientId: client1
