server:
  port: 8080
logging:
  config: classpath:logback.xml

spring:
  application:
    name: simple_feign_server
  jmx:
    default-domain: OKService_feign_server


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

simple-feign-meta:
  okService: OKService