server:
  port: 8083
logging:
  config: classpath:logback.xml

spring:
  application:
    name: ok-service-3
  jmx:
    default-domain: OKService_client3

eureka:
  client:
    enabled: false

ok-service-meta:
  clientId: client3