server:
  port: 8080
logging:
  config: classpath:logback.xml


management:
  endpoints:
    web:
      exposure:
        include:
        - info
        - routes

spring:
  application:
    name: simple_zuul_witout_eureka
  jmx:
    default-domain: simple_zuul_witout_eureka

eureka:
  client:
    enabled: false

zuul:
  ribbon:
    eager-load:
      enabled: true
  routes:
    to-zuul:
      path: /tozuul/**
      url: forward:/examples
    to-zuul2:
      path: /tozuul2
      url: forward:/examples
    to-service-3:
      path: /demo/*/client3/**
      url: http://localhost:8083/
    to-service-2:
      path: /demo/abc/**
      url: http://localhost:8082/
    to-service-1:
      path: /demo/**
      url: http://localhost:8081/



