server:
  port: 8080
logging:
  config: classpath:logback.xml

management:
  server:
    port: 8888

spring:
  application:
    name: simple_zuul_witout_eureka
  jmx:
    default-domain: simple_zuul_witout_eureka

eureka:
  client:
    enabled: false

zuul:
  ribbon:
    eager-load:
      enabled: true
  routes:
    ignoredPatterns: /**/zuul/**,/info
    to-service-3:
      path: /demo/*/client3/**
      url: http://localhost:8083/
    to-service-2:
      path: /demo/abc/**
      url: http://localhost:8082/
    to-service-1:
      path: /demo/**
      url: http://localhost:8081/


