server:
  port: 8080
logging:
  config: classpath:logback.xml

management:
  server:
    port: 8888

spring:
  application:
    name: simple_zuul_witout_eureka
  jmx:
    default-domain: simple_zuul_witout_eureka

eureka:
  client:
    enabled: false

zuul:
  ribbon:
    eager-load:
      enabled: true
  routes:
    to-service-3:
      path: /demo/*/client3/**
      url: http://localhost:8083/
    to-service-2:
      path: /demo/abc/**
      url: client2
    to-service-1:
      path: /demo/**
      serviceId: client1

hystrix:
  command:
    client1:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    client2:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
client1:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: http://localhost:8081/
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    retryableStatusCodes: 404
    MaxConnectionsPerHost: 100
client2:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: http://localhost:8082/
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    retryableStatusCodes: 404
    MaxConnectionsPerHost: 100